// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOTjCcDeO9dBb5rXerFvmwN3r-c33FP8k',
    appId: '1:739988071875:web:f7d14eba1c96a11bb4c976',
    messagingSenderId: '739988071875',
    projectId: 'vanber-project',
    authDomain: 'vanber-project.firebaseapp.com',
    storageBucket: 'vanber-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfaRzrLlncp1T869o8MWu-o5LMAo7INoU',
    appId: '1:739988071875:android:0eda93d83032c379b4c976',
    messagingSenderId: '739988071875',
    projectId: 'vanber-project',
    storageBucket: 'vanber-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5M6ziJxnPa4OOB7WcnPGO7eqdXub3S5Q',
    appId: '1:739988071875:ios:f07916489ed44ab1b4c976',
    messagingSenderId: '739988071875',
    projectId: 'vanber-project',
    storageBucket: 'vanber-project.firebasestorage.app',
    iosBundleId: 'com.example.vanBerPassenger',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5M6ziJxnPa4OOB7WcnPGO7eqdXub3S5Q',
    appId: '1:739988071875:ios:f07916489ed44ab1b4c976',
    messagingSenderId: '739988071875',
    projectId: 'vanber-project',
    storageBucket: 'vanber-project.firebasestorage.app',
    iosBundleId: 'com.example.vanBerPassenger',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOTjCcDeO9dBb5rXerFvmwN3r-c33FP8k',
    appId: '1:739988071875:web:f08df4217a7c682eb4c976',
    messagingSenderId: '739988071875',
    projectId: 'vanber-project',
    authDomain: 'vanber-project.firebaseapp.com',
    storageBucket: 'vanber-project.firebasestorage.app',
  );
}
